### ISSUE TITLE
PEER TO PEER CODE REVIEW ON 11TH NOV 2022

### ISSUE THREAD

**Issue by Balikuddembe** [Balikuddembe/ToDo-List-using-ES6-and-Webpack#10]
Hello team 👋 ,Feel free to make any comment regarding my code.
Regards 😄

**Comment by sebalp100** [comment]
Hi @Balikuddembe , your code looks great 👍 

✔️ Follows JS best practices
✔️ Good use of modules
✔️ All the methods work as per the requirements

**Comment by dialite** [comment]
Hi @Balikuddembe,

You have nice code layout and linkage. For best practice, it is more appropriate to place your export and imports at that top of the page.

- In 'populateTaskList.js', the class export was stated at the base of the page. You can move it upward.

**Comment by osamaashraf6** [comment]
## This is my review of this project. 👎 

### High Lights 💯 


- [x] Good commit messages.
- [x] Descriptive READme file in a professional way.
- [x] No linters errors. 
- [x] Good usage in correcting GitHub flow
- [x] Beautiful UI. 
- [x] Nice design.
- [x] Good code organization👍.
- [x] Follow our list of best practices for HTML & CSS.
- [x] Follow our list of best practices for JavaScript.


![ThumbsUpOkayGIF](https://user-images.githubusercontent.com/83360636/201356690-4471a15f-6782-44e2-a193-a5723b3369fe.gif)
